export const ADD_GENRE = "ADD_GENRE";
export const DELETE_GENRE = "DELETE_GENRE";
export const ADD_RELEASE_YEAR = "ADD_RELEASE_YEAR";
export const ADD_MOVIE_TITLE = "ADD_MOVIE_TITLE";
export const FETCH_MOVIES_REQUEST = "FETCH_MOVIES_REQUEST";
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export const FETCH_MOVIES_FAILURE = "FETCH_MOVIES_FAILURE";
